fix(backend): adds transitive dependency expo-secure-store (#959)
## Type of PR (check all applicable)

- [ ] Feature
- [x] Bug Fix
- [ ] Refactor
- [ ] Documentation Update
- [ ] Performance Improvement
- [ ] Test Update
- [ ] Chore
- [ ] Other (please describe)

## Description

This pull request primarily updates project dependencies, including the
addition of a new package and several version bumps. The most
significant change is the introduction of the `expo-secure-store`
package, which is now included in both the `package.json` and lockfile.
Other changes involve minor dependency updates and adjustments.

Primarily due to:

```
ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY  Broken lockfile: no entry for 'expo-secure-store@15.0.8(expo@54.0.31)' in pnpm-lock.yaml
1.656 
1.656 This issue is probably caused by a badly resolved merge conflict.
1.656 To fix the lockfile, run 'pnpm install --no-frozen-lockfile'.
------
Dockerfile:37
--------------------
  35 |     
  36 |     # First install the dependencies (as they change less often)
  37 | >>> RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile
  38 |     
  39 |     # Copy source code of isolated subworkspace
--------------------
ERROR: failed to build: failed to solve: process "/bin/sh -c pnpm install --frozen-lockfile" did not complete successfully: exit code: 1
Error: Process completed with exit code 1.
```